"""Generic NRE training loop, shared by hitnet and chargenet.

The two networks differ only in their (obs, hyp) arrays; 1.x's two near-identical
train functions collapse into ``fit``. Marginal (label-0) pairs are built inside the
jitted step by permuting hypothesis indices within the batch.

Memory model: ``obs`` and ``hyp`` stay on the host and may be numpy memmaps
(``HitStore`` arrays) — only the current batch is copied and sent to the device, so
dataset size is bounded by disk, not RAM or device memory. For hitnet, pass the
per-event hypothesis table plus ``hyp_index=event_id``: the per-hit hypothesis rows
are gathered per batch and never materialized for the full dataset.
"""

import time
from dataclasses import dataclass

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np
import optax

from hitman.data.pipeline import block_shuffled_rows, prefetch
from hitman.train.losses import nre_loss


@dataclass
class FitResult:
    model: object
    train_loss: list
    val_loss: list
    best_epoch: int


def _batch_loss(model, obs, hyp, key, balance_weight, weights=None):
    # obs may be an array or a tuple of arrays (e.g. FrameHitNet's (pmt_id, t));
    # the marginal pairing permutes hypotheses, so size the permutation from hyp.
    joint = jax.vmap(model)(obs, hyp)
    marginal = jax.vmap(model)(obs, hyp[jax.random.permutation(key, hyp.shape[0])])
    return nre_loss(joint, marginal, balance_weight, weights)


def _unpack_batch(out):
    """A make_batch may return (obs, hyp) or (obs, hyp, weights); normalize to 3."""
    if len(out) == 3:
        return out
    obs, hyp = out
    return obs, hyp, None


def _gather(obs, hyp, hyp_index, rows):
    """Host-side batch materialization: numpy fancy-index (memmap-safe) -> device."""
    obs_b = jnp.asarray(obs[rows])
    hyp_rows = hyp_index[rows] if hyp_index is not None else rows
    return obs_b, jnp.asarray(hyp[hyp_rows])


def fit(
    model,
    obs,
    hyp,
    *,
    key,
    hyp_index=None,
    batch_size: int = 2**14,
    learning_rate: float = 1e-3,
    max_epochs: int = 1000,
    patience: int = 50,
    val_fraction: float = 0.1,
    max_val_rows: int = 2**16,
    balance_weight: float = 0.0,
    verbose: bool = True,
) -> FitResult:
    """Train an NRE model with early stopping.

    Parameters
    ----------
    obs, hyp : array-like (numpy or memmap)
        Aligned rows: row i of obs was generated by hypothesis row
        ``hyp_index[i]`` (or ``hyp[i]`` when ``hyp_index`` is None).
        Chargenet: obs = per-event charge, hyp = per-event hypotheses.
        Hitnet: obs = flat hits, hyp = per-event hypotheses, hyp_index = event_id.
    max_val_rows : int
        Cap on validation rows (subsampled from the validation split) so validation
        cost and device memory stay bounded on large datasets.
    """
    n = len(obs)
    n_val = max(int(n * val_fraction), 1)
    val_rows = np.arange(n - n_val, n)
    if n_val > max_val_rows:
        val_rows = val_rows[:: n_val // max_val_rows + 1][:max_val_rows]
    obs_v, hyp_v = _gather(obs, hyp, hyp_index, val_rows)

    optimizer = optax.adam(learning_rate)
    opt_state = optimizer.init(eqx.filter(model, eqx.is_inexact_array))

    @eqx.filter_jit
    def train_step(model, opt_state, obs_b, hyp_b, key):
        loss, grads = eqx.filter_value_and_grad(_batch_loss)(
            model, obs_b, hyp_b, key, balance_weight
        )
        updates, opt_state = optimizer.update(grads, opt_state)
        model = eqx.apply_updates(model, updates)
        return model, opt_state, loss

    @eqx.filter_jit
    def val_loss_fn(model, key):
        return _batch_loss(model, obs_v, hyp_v, key, balance_weight)

    n_train = n - n_val
    batch_size = min(batch_size, n_train)  # small datasets: one full batch per epoch
    rng = np.random.default_rng(int(jax.random.randint(key, (), 0, 2**31 - 1)))
    best = (np.inf, 0, model)
    train_hist, val_hist = [], []

    for epoch in range(max_epochs):
        t0 = time.time()
        # Block-shuffled, prefetched batches: memmap reads stay near-sequential and
        # the next batch is staged on a worker thread while the device trains.
        batches = (
            _gather(obs, hyp, hyp_index, rows)
            for rows in block_shuffled_rows(n_train, batch_size, rng)
        )
        epoch_loss, steps = 0.0, 0
        for obs_b, hyp_b in prefetch(batches, size=2):
            key, step_key = jax.random.split(key)
            model, opt_state, loss = train_step(model, opt_state, obs_b, hyp_b, step_key)
            epoch_loss += float(loss)
            steps += 1
        steps_per_epoch = max(steps, 1)
        key, val_key = jax.random.split(key)
        v = float(val_loss_fn(model, val_key))
        train_hist.append(epoch_loss / steps_per_epoch)
        val_hist.append(v)
        if v < best[0]:
            best = (v, epoch, model)
        if verbose:
            print(
                f"epoch {epoch:4d}  train {train_hist[-1]:.5f}  val {v:.5f}  "
                f"({time.time() - t0:.1f}s)",
                flush=True,
            )
        if epoch - best[1] >= patience:
            break

    return FitResult(model=best[2], train_loss=train_hist, val_loss=val_hist, best_epoch=best[1])
