"""Generic NRE training loop, shared by hitnet and chargenet.

The two networks differ only in their (obs, hyp) arrays; 1.x's two near-identical
train functions collapse into ``fit``. Marginal (label-0) pairs are built inside the
jitted step by permuting hypothesis indices within the batch.
"""

import time
from dataclasses import dataclass

import equinox as eqx
import jax
import jax.numpy as jnp
import numpy as np
import optax

from hitman.train.losses import nre_loss


@dataclass
class FitResult:
    model: object
    train_loss: list
    val_loss: list
    best_epoch: int


def _batch_loss(model, obs, hyp, key, balance_weight):
    joint = jax.vmap(model)(obs, hyp)
    marginal = jax.vmap(model)(obs, hyp[jax.random.permutation(key, obs.shape[0])])
    return nre_loss(joint, marginal, balance_weight)


def fit(
    model,
    obs: np.ndarray,
    hyp: np.ndarray,
    *,
    key,
    batch_size: int = 2**14,
    learning_rate: float = 1e-3,
    max_epochs: int = 1000,
    patience: int = 50,
    val_fraction: float = 0.1,
    balance_weight: float = 0.0,
    verbose: bool = True,
) -> FitResult:
    """Train an NRE model on aligned (obs, hyp) rows with early stopping.

    obs/hyp rows must be index-aligned (row i of obs was generated by row i of hyp);
    for hitnet pass per-hit rows (obs=hits, hyp=hyp[event_id]), for chargenet
    per-event rows.
    """
    n = len(obs)
    n_val = max(int(n * val_fraction), 1)
    obs_t, hyp_t = jnp.asarray(obs[:-n_val]), jnp.asarray(hyp[:-n_val])
    obs_v, hyp_v = jnp.asarray(obs[-n_val:]), jnp.asarray(hyp[-n_val:])

    optimizer = optax.adam(learning_rate)
    opt_state = optimizer.init(eqx.filter(model, eqx.is_inexact_array))

    @eqx.filter_jit
    def train_step(model, opt_state, obs_b, hyp_b, key):
        loss, grads = eqx.filter_value_and_grad(_batch_loss)(
            model, obs_b, hyp_b, key, balance_weight
        )
        updates, opt_state = optimizer.update(grads, opt_state)
        model = eqx.apply_updates(model, updates)
        return model, opt_state, loss

    @eqx.filter_jit
    def val_loss_fn(model, key):
        return _batch_loss(model, obs_v, hyp_v, key, balance_weight)

    n_train = len(obs_t)
    steps_per_epoch = max(n_train // batch_size, 1)
    best = (np.inf, 0, model)
    train_hist, val_hist = [], []

    for epoch in range(max_epochs):
        t0 = time.time()
        key, shuffle_key = jax.random.split(key)
        order = jax.random.permutation(shuffle_key, n_train)
        epoch_loss = 0.0
        for step in range(steps_per_epoch):
            idx = order[step * batch_size : (step + 1) * batch_size]
            key, step_key = jax.random.split(key)
            model, opt_state, loss = train_step(model, opt_state, obs_t[idx], hyp_t[idx], step_key)
            epoch_loss += float(loss)
        key, val_key = jax.random.split(key)
        v = float(val_loss_fn(model, val_key))
        train_hist.append(epoch_loss / steps_per_epoch)
        val_hist.append(v)
        if v < best[0]:
            best = (v, epoch, model)
        if verbose:
            print(
                f"epoch {epoch:4d}  train {train_hist[-1]:.5f}  val {v:.5f}  "
                f"({time.time() - t0:.1f}s)",
                flush=True,
            )
        if epoch - best[1] >= patience:
            break

    return FitResult(model=best[2], train_loss=train_hist, val_loss=val_hist, best_epoch=best[1])
